export enum MutationTypes {
  SET_THEME = 'SET_THEME',
  SET_SHOWSIDEBAR = 'SET_SHOWSIDEBAR',
  SET_LANG = 'SET_LANG',
  // SET_TRANSLATIONS = 'SET_TRANSLATIONS',

  SET_LOADING = 'SET_LOADING',
  SET_SHOW_RESULT = 'SET_SHOW_RESULT',
  SET_POSTS = 'SET_POSTS',
  SET_PERSON_NUMBER = 'SET_PERSON_NUMBER',
}